/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngat.opsgui.xcomp;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.SimpleTimeZone;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;
import ngat.astrometry.AstrometrySimulator;
import ngat.astrometry.AstrometrySimulatorListener;

/**
 *
 * @author eng
 */
public class AstroSimControlPanel extends javax.swing.JPanel implements AstrometrySimulatorListener {

    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    private static final SimpleTimeZone UTC = new SimpleTimeZone(0, "UTC");

    private AstrometrySimulator simulator;

    private long startTime;

    private long endTime;

    private long simulationTime;

    private long runStepLength;

    private long delay;

    /**
     * Creates new form AstroSimControlPanel
     */
    public AstroSimControlPanel(AstrometrySimulator simulator) {
        sdf.setTimeZone(UTC);
        this.simulator = simulator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        simulationTimeField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        runStepCombo = new javax.swing.JComboBox();
        delayCombo = new javax.swing.JComboBox();
        startTimeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        endTimeField = new javax.swing.JTextField();
        configButton = new javax.swing.JButton();
        modeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        infoButton = new javax.swing.JButton();
        gotoStartButton = new javax.swing.JButton();
        fastBackwardButton = new javax.swing.JButton();
        stepBackwardButton = new javax.swing.JButton();
        runForwardButton = new javax.swing.JButton();
        fastForwardButton = new javax.swing.JButton();
        runbackwardButton = new javax.swing.JButton();
        gotoEndButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stepForwardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 2, 13)); // NOI18N
        jLabel2.setText("Simulation time");

        simulationTimeField.setEditable(false);

        jLabel3.setText("Run step");

        jLabel5.setText("min");

        jLabel6.setText("sec");

        jLabel7.setText("Start");

        jLabel4.setText("Delay");

        jLabel9.setText("UTC");

        jLabel10.setText("UTC");

        runStepCombo.setModel(createStepModel());

        delayCombo.setModel(createDelayModel());

        jLabel8.setText("Finish");

        configButton.setText("Config");
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        modeLabel.setFont(new java.awt.Font("DejaVu Sans", 3, 13)); // NOI18N
        modeLabel.setForeground(new java.awt.Color(235, 23, 171));
        modeLabel.setText("Idle");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(runStepCombo, 0, 68, Short.MAX_VALUE)
                            .addComponent(delayCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modeLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(configButton))))
                    .addComponent(endTimeField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startTimeField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runStepCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(modeLabel))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(delayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(configButton))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(startTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(endTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/info-icon.png"))); // NOI18N
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        gotoStartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/goto-start-icon.png"))); // NOI18N
        gotoStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoStartButtonActionPerformed(evt);
            }
        });

        fastBackwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/fast-backward-icon.png"))); // NOI18N
        fastBackwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastBackwardButtonActionPerformed(evt);
            }
        });

        stepBackwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/step-backward-icon.png"))); // NOI18N
        stepBackwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepBackwardButtonActionPerformed(evt);
            }
        });

        runForwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/run-forward-icon.png"))); // NOI18N
        runForwardButton.setBorderPainted(false);
        runForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runForwardButtonActionPerformed(evt);
            }
        });

        fastForwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/fast-forward-icon.png"))); // NOI18N
        fastForwardButton.setBorderPainted(false);
        fastForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastForwardButtonActionPerformed(evt);
            }
        });

        runbackwardButton.setIcon(new javax.swing.ImageIcon("/home/eng/opsgui/icons/run-backward-icon.png")); // NOI18N
        runbackwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runbackwardButtonActionPerformed(evt);
            }
        });

        gotoEndButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/goto-end-icon.png"))); // NOI18N
        gotoEndButton.setBorderPainted(false);
        gotoEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoEndButtonActionPerformed(evt);
            }
        });

        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/pause-icon.png"))); // NOI18N
        pauseButton.setBorderPainted(false);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        stepForwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/step-forward-icon.png"))); // NOI18N
        stepForwardButton.setBorderPainted(false);
        stepForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepForwardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gotoStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fastBackwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepBackwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runbackwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(runForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fastForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stepBackwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gotoStartButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fastBackwardButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(runbackwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(gotoEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stepForwardButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(fastForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("UTC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(simulationTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(simulationTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        JOptionPane.showMessageDialog(this,
                "Use the play controls to advance the simulation",
                "Astrometry Simulator Control",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void gotoStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoStartButtonActionPerformed
        simulator.gotoStart();
    }//GEN-LAST:event_gotoStartButtonActionPerformed

    private void fastBackwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastBackwardButtonActionPerformed
        getRunParameters(10);
        simulator.runSimulation(-runStepLength, delay);
    }//GEN-LAST:event_fastBackwardButtonActionPerformed

    private void stepBackwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepBackwardButtonActionPerformed
        getRunParameters(1);
        simulator.stepSimulation(-runStepLength);
    }//GEN-LAST:event_stepBackwardButtonActionPerformed

    private void runForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runForwardButtonActionPerformed
        getRunParameters(1);
        simulator.runSimulation(runStepLength, delay);
    }//GEN-LAST:event_runForwardButtonActionPerformed

    private void stepForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepForwardButtonActionPerformed
        getRunParameters(1);
        simulator.stepSimulation(runStepLength);
    }//GEN-LAST:event_stepForwardButtonActionPerformed

    private void fastForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastForwardButtonActionPerformed
        getRunParameters(10);
        simulator.runSimulation(runStepLength, delay);
    }//GEN-LAST:event_fastForwardButtonActionPerformed

    private void runbackwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runbackwardButtonActionPerformed
        getRunParameters(1);
        simulator.runSimulation(-runStepLength, delay);
    }//GEN-LAST:event_runbackwardButtonActionPerformed

    private void gotoEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoEndButtonActionPerformed
        simulator.gotoEnd();
    }//GEN-LAST:event_gotoEndButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        simulator.pauseSimulation();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        try {
            startTime = (sdf.parse(startTimeField.getText())).getTime();
            endTime = (sdf.parse(endTimeField.getText())).getTime();
        } catch (Exception e) {
            e.printStackTrace();
        }

        simulator.configure(startTime, endTime);
    }//GEN-LAST:event_configButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configButton;
    private javax.swing.JComboBox delayCombo;
    private javax.swing.JTextField endTimeField;
    private javax.swing.JButton fastBackwardButton;
    private javax.swing.JButton fastForwardButton;
    private javax.swing.JButton gotoEndButton;
    private javax.swing.JButton gotoStartButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton runForwardButton;
    private javax.swing.JComboBox runStepCombo;
    private javax.swing.JButton runbackwardButton;
    private javax.swing.JTextField simulationTimeField;
    private javax.swing.JTextField startTimeField;
    private javax.swing.JButton stepBackwardButton;
    private javax.swing.JButton stepForwardButton;
    // End of variables declaration//GEN-END:variables

    private ComboBoxModel createStepModel() {
        Integer[] items = new Integer[]{1, 2, 5, 10, 15, 30, 60, 120};
        DefaultComboBoxModel model = new DefaultComboBoxModel(items);

        return model;
    }

    private ComboBoxModel createDelayModel() {
        Integer[] items = new Integer[]{1, 2, 4, 10};
        DefaultComboBoxModel model = new DefaultComboBoxModel(items);

        return model;
    }

    private void getRunParameters(int multiply) {
        try {
            runStepLength = multiply * 60000 * ((Integer) runStepCombo.getSelectedItem()).longValue();
            delay = 1000 * ((Integer) delayCombo.getSelectedItem()).longValue();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void simulationRunning(boolean run) {
        if (run) {
            modeLabel.setForeground(Color.GREEN);
            modeLabel.setText("Run...");
        } else {
            modeLabel.setForeground(Color.MAGENTA);
            modeLabel.setText("Idle");
        }
    }

    @Override
    public void simulationTimeUpdated(long time) {
        simulationTime = time;
        simulationTimeField.setText(sdf.format(new Date(simulationTime)));

        boolean canGoFwd = (simulationTime < endTime);
        boolean cangoBack = (simulationTime > startTime);

        stepBackwardButton.setEnabled(cangoBack);
        gotoStartButton.setEnabled(cangoBack);
        runbackwardButton.setEnabled(cangoBack);
        fastBackwardButton.setEnabled(cangoBack);

        stepForwardButton.setEnabled(canGoFwd);
        gotoEndButton.setEnabled(canGoFwd);
        runForwardButton.setEnabled(canGoFwd);
        fastForwardButton.setEnabled(canGoFwd);

    }

  

}
