/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngat.opsgui.login;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author eng
 */
public class UserDetailsPanel extends javax.swing.JPanel {

    private LoginPanel loginPanel;

    private String iconPath;

    private boolean create;

    private JDialog dialog;

    /**
     * Creates new form UserDetailsPanel
     */
    public UserDetailsPanel(LoginPanel loginPanel) {
        this.loginPanel = loginPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iconButton = new javax.swing.JButton();

        jLabel1.setText("Username");

        jLabel2.setText("Title");

        titleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dr", "Mr", "Ms", "Miss", "Mrs", "Prof", "Sir" }));

        jLabel4.setText("First");

        jLabel5.setText("Surname");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonHandler(evt);
            }
        });

        jButton2.setText("Cancel");

        iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngat/opsgui/resources/head_icon.jpg"))); // NOI18N
        iconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(9, 9, 9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 53, Short.MAX_VALUE))
                            .addComponent(userNameField))
                        .addGap(7, 7, 7)
                        .addComponent(iconButton)
                        .addGap(30, 30, 30))
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(iconButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19)
                .addComponent(jLabel3))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void createNewUserDialog(JFrame frame) {
        create = true;

        dialog = new JDialog(frame);
        dialog.getContentPane().add(this);
        dialog.pack();
        dialog.setVisible(true);
    }

    public void createEditUserDialog(JFrame frame, UserDescriptor udesc) {
        create = false;
        userNameField.setText(udesc.getId());
        userNameField.setEditable(false);
        titleCombo.setSelectedItem(udesc.getTitle());
        firstNameField.setText(udesc.getFirstName());
        lastNameField.setText(udesc.getLastName());

        //iconButton.setIcon(new ImageIcon(udesc.getIconPath()));
        dialog = new JDialog(frame);
        dialog.getContentPane().add(this);
        dialog.pack();
        dialog.setVisible(true);
    }

    private void iconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconButtonActionPerformed

        // allow user to change the default icon
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new ImageFileFilter());
       // ImagePreviewPanel ipp = new ImagePreviewPanel();
        //  chooser.setAccessory(ipp);
        //  chooser.addPropertyChangeListener(ipp);
        int approve = chooser.showDialog(this, "Select");
        if (approve == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();

            // how big is this image ?
            try {
                BufferedImage image = ImageIO.read(f);
                int w = image.getWidth(null);
                int h = image.getHeight(null);

                int neww = 0;
                int newh = 0;
                // choose the larger and scale
                if (w > h) {
                    neww = 48;
                    newh = 48 * h / w;
                } else {
                    newh = 48;
                    neww = 48 * w / h;
                }

                Image image2 = image.getScaledInstance(neww, newh, Image.SCALE_SMOOTH);
                iconButton.setIcon(new ImageIcon(image2));

                String userName = userNameField.getText().trim();
                System.err.println("Image size will become: "+neww+"x"+newh);
                
                iconPath = new String("/Users/eng/opsgui/icons/wee_" + userName + ".png");

                // save the reduced icon to a file in the icon subdir
                //ImageIO.write((RenderedImage) image2, "png", new File(iconPath));
                saveImage(image2, new File(iconPath));
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_iconButtonActionPerformed

    private void saveImage(Image image, File file) throws Exception {
        Dimension d = new Dimension(image.getWidth(null), image.getHeight(null));
        JPanel p = new JPanel();
        p.setPreferredSize(d);
        BufferedImage imagew = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
        // call the Component's paint method, using
        // the Graphics object of the image.
        p.paint(imagew.getGraphics());
        imagew.getGraphics().dispose();
        // String datestr = udf.format(new Date(start));
        System.err.println("Writing to: " + file.getName());
        ImageIO.write(imagew, "png", file);
    }

    private void saveButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonHandler

        String userName = userNameField.getText().trim();
        String title = (String) titleCombo.getSelectedItem();
        String first = firstNameField.getText().trim();
        String last = lastNameField.getText().trim();

        UserDescriptor udesc = new UserDescriptor(userName, title, first, last);
        udesc.setIconPath(iconPath);

        if (create) {
            loginPanel.addUser(udesc);
        } else {
            loginPanel.editUser(udesc);
        }

        if (dialog != null) {
            dialog.dispose();
        }

    }//GEN-LAST:event_saveButtonHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstNameField;
    private javax.swing.JButton iconButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JComboBox titleCombo;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    private static class ImageFileFilter extends FileFilter {

        public ImageFileFilter() {
        }

        @Override
        public boolean accept(File f) {
            if (f.isDirectory()) {
                return true;
            }
            String name = f.getName();
            if (name.endsWith("jpg") || name.endsWith("png") || name.endsWith("gif") || name.endsWith("JPG")) {
                return true;
            }
            return false;
        }

        @Override
        public String getDescription() {
            return "Image file";
        }
    }

}
