/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ngat.opsgui.beans;

import ngat.astrometry.AstroLib;
import ngat.astrometry.BasicSite;
import ngat.astrometry.BasicTargetTrackCalculatorFactory;
import ngat.astrometry.JAstroSlalib;
import ngat.astrometry.TargetTrackCalculator;
import ngat.astrometry.TargetTrackCalculatorFactory;
import ngat.astrometry.approximate.AlternativeTargetTrackCalculatorFactory;
import ngat.astrometry.approximate.BasicAstroLibImpl;
import ngat.phase2.IRotatorConfig;
import ngat.phase2.ITarget;

/**
 *
 * @author eng
 */
public class NewJPanel extends javax.swing.JPanel {

    private TargetTrackCalculatorFactory tcf;
    private BasicSite site;
    
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        
        tcf = new AlternativeTargetTrackCalculatorFactory();
        AstroLib lib = new BasicAstroLibImpl();
         site = new BasicSite("LT", Math.toRadians(28.0), Math.toRadians(-17.0));
         
    
        rp1.setInstOffset(Math.toRadians(50.0));
         
        rp1.setRotatorMode(IRotatorConfig.MOUNT);
      
        rp1.setupCalculator(site, lib, tcf);
      
        
    
    }

    public void updateTarget(ITarget target, long s, long e) throws Exception {
        System.err.println("Using:"+tcf+" to create track for: "+target);
        TargetTrackCalculator track = tcf.getTrackCalculator(target, site);
         System.err.println("Goot track: "+track);
         System.err.println("Update rp1...");
        rp1.updateTrack(track, s, e, 1200000);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rp1 = new ngat.astrometry.components.RotatorMountTimePanel2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout rp1Layout = new javax.swing.GroupLayout(rp1);
        rp1.setLayout(rp1Layout);
        rp1Layout.setHorizontalGroup(
            rp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        rp1Layout.setVerticalGroup(
            rp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jLabel1.setText("a little label to pad stuff out dont you know");

        jLabel2.setText("another little old label dont you know at all at all");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private ngat.astrometry.components.RotatorMountTimePanel2 rp1;
    // End of variables declaration//GEN-END:variables
}
